# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/coworking?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: springuser
        password: springpassword
    jpa:
        hibernate:
            ddl-auto: none
        #        again, this could be dangerous as it could expose passwords
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    jackson:
        deserialization:
            fail-on-unknown-properties: true
coworking:
    security:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        jwt-validity-in-seconds: 86400
        # Token is valid 30 days
        jwt-validity-in-seconds-for-remember-me: 2592000
    cors:
        allowed-origins: "*"
        allowed-methods: POST, PUT, GET, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
